// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Article0: typeof import('./src/components/Articles/Article0.vue')['default']
    Article1: typeof import('./src/components/Articles/Article1.vue')['default']
    Article2: typeof import('./src/components/Articles/Article2.vue')['default']
    Article3: typeof import('./src/components/Articles/Article3.vue')['default']
    ArticleItem: typeof import('./src/components/ArticleItem.vue')['default']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPageHeader: typeof import("element-plus/es")["ElPageHeader"];
    ElSubMenu: typeof import("element-plus/es")["ElSubMenu"];
    NavigationBar: typeof import('./src/components/NavigationBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
